2025-10-14 15:10:19,246 INFO     Running data_generator_swes.py --filename data/data_valid_swes_nref_4_0.0001.h5 --nref 4 --omega 7.292e-5 --g 9.8 --nt 10 --tfinalmax 0.0001 --nsamples 32
2025-10-14 15:10:20,009 ERROR    Gusto is logging this unhandled exception:
Traceback (most recent call last):
  File "/home/katie795/NeuralPDE_workspace/NeuralPDE/src/data_generator_swes.py", line 98, in <module>
    dataset.prepare_for_model()
  File "/home/katie795/NeuralPDE_workspace/NeuralPDE/src/neural_pde/datasets.py", line 463, in prepare_for_model
    h_inp.assign(h1)
  File "petsc4py/PETSc/Log.pyx", line 250, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "petsc4py/PETSc/Log.pyx", line 251, in petsc4py.PETSc.Log.EventDecorator.decorator.wrapped_func
  File "/home/katie795/software/venv-firedrake/lib/python3.12/site-packages/firedrake/adjoint_utils/function.py", line 116, in wrapper
    ret = assign(self, other, *args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/katie795/software/venv-firedrake/lib/python3.12/site-packages/firedrake/function.py", line 461, in assign
    Assigner(self, expr, subset).assign()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/katie795/software/venv-firedrake/lib/python3.12/site-packages/firedrake/assign.py", line 152, in __init__
    raise ValueError("All functions in the expression must have the same "
ValueError: All functions in the expression must have the same element as the assignee
